print('*' '\t\t\t *' '\t*' '\t' '* * * * *' '\t\t***' ' \t\t*' '\t\t\t*' '\t*' '\t\t\t\t*')
print(' *' '\t\t\t*' '\t ' '\t\t*' '\t\t   *' '   *' '\t\t*' '\t\t\t' '\t  *' '\t\t\t  *')
print('  *' '\t\t   *' '\t*' '\t\t*' '\t\t  *' '\t    *' '\t\t*' '\t\t\t*' '\t\t*' '\t\t*')
print('   *' '\t  *' '\t\t*' '\t\t*' '\t\t * * * * *' '\t\t*' '\t\t\t*' '\t\t  *'   '   *')
print('\t*' '\t *' '\t\t*' '\t\t*' '\t\t*' '\t\t  *' '\t\t*' '\t\t\t*' '\t\t    *')
print('\t *' ' ' ' *' '\t\t*' '\t\t*' '\t   *' '\t\t   *' '\t*' '\t\t\t*' '\t\t  *')
print('\t  **' '\t\t*' '\t\t*' '\t  *' '\t\t\t    *' '\t* * * * *' '\t*' '\t\t*' '\n')
print('*' * 82 + '\n')